/**
 * TermsScreen - Phase 4: App Store Preparation
 */

import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Platform,
} from 'react-native';
import { useTheme } from '../contexts/ThemeContext';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../types';

type Props = NativeStackScreenProps<RootStackParamList, 'Terms'>;

export function TermsScreen({ navigation }: Props) {
  const { theme } = useTheme();

  return (
    <View style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={[styles.header, { backgroundColor: theme.colors.surface }]}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={[styles.back, { color: theme.colors.primary }]}>← Back</Text>
        </TouchableOpacity>
        <Text style={[styles.title, { color: theme.colors.text }]}>Terms of Service</Text>
        <View style={{ width: 50 }} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={[styles.lastUpdated, { color: theme.colors.textTertiary }]}>
          Last updated: January 2025
        </Text>

        <Section title="1. Acceptance of Terms" theme={theme}>
          By downloading, installing, or using FlirtKey ("App"), you agree to be bound by these
          Terms of Service ("Terms"). If you do not agree, do not use the App.
        </Section>

        <Section title="2. Description of Service" theme={theme}>
          FlirtKey is an AI-powered conversation assistant designed to help users craft messages
          for dating and social interactions. The App provides suggestions, coaching tips, and
          conversation analysis tools. FlirtKey is a tool — it does not guarantee any particular
          social or romantic outcome.
        </Section>

        <Section title="3. Eligibility" theme={theme}>
          You must be at least 17 years old to use FlirtKey. By using the App, you represent
          and warrant that you meet this age requirement.
        </Section>

        <Section title="4. User Responsibilities" theme={theme}>
          You are solely responsible for:{'\n\n'}
          • How you use AI-generated suggestions in your conversations{'\n'}
          • Providing your own OpenAI API key and managing its costs{'\n'}
          • Ensuring your use of the App complies with applicable laws{'\n'}
          • Not using the App for harassment, spam, or any unlawful purpose{'\n'}
          • The accuracy of any information you provide within the App
        </Section>

        <Section title="5. AI-Generated Content" theme={theme}>
          Suggestions generated by FlirtKey are created using artificial intelligence and are
          provided for informational and entertainment purposes only. We do not guarantee the
          accuracy, appropriateness, or effectiveness of any AI-generated content. You should
          always review and personalize suggestions before sending them. You use AI-generated
          content at your own discretion and risk.
        </Section>

        <Section title="6. Subscription & Payments" theme={theme}>
          FlirtKey offers free and premium (Pro) tiers:{'\n\n'}
          • Free: Limited daily suggestions and features{'\n'}
          • Pro: Unlimited suggestions and all features{'\n'}
          • Lifetime: One-time purchase for permanent Pro access{'\n\n'}
          Subscriptions are billed through the Apple App Store or Google Play Store and are
          subject to their respective terms. Subscriptions auto-renew unless cancelled at least
          24 hours before the end of the current period. Refunds are handled by the respective
          app store.
        </Section>

        <Section title="7. API Key Usage" theme={theme}>
          FlirtKey requires an OpenAI API key to function. You are responsible for obtaining
          and maintaining your API key and any associated costs. We store your API key locally
          on your device and do not transmit it to our servers.
        </Section>

        <Section title="8. Intellectual Property" theme={theme}>
          FlirtKey, its design, features, and content (excluding AI-generated suggestions) are
          the intellectual property of KivoSoft. You may not copy, modify, distribute, or
          reverse-engineer any part of the App without written permission.
        </Section>

        <Section title="9. Disclaimer of Warranties" theme={theme}>
          THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
          EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE,
          OR THAT AI-GENERATED CONTENT WILL BE ACCURATE OR APPROPRIATE FOR YOUR SITUATION.
        </Section>

        <Section title="10. Limitation of Liability" theme={theme}>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, KIVOSOFT SHALL NOT BE LIABLE FOR ANY INDIRECT,
          INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE
          APP, INCLUDING BUT NOT LIMITED TO DAMAGES ARISING FROM SOCIAL INTERACTIONS BASED ON
          AI-GENERATED SUGGESTIONS.
        </Section>

        <Section title="11. Termination" theme={theme}>
          We reserve the right to terminate or suspend your access to the App at any time,
          without notice, for conduct that we believe violates these Terms or is harmful to
          other users or the App.
        </Section>

        <Section title="12. Changes to Terms" theme={theme}>
          We may update these Terms from time to time. Continued use of the App after changes
          constitutes acceptance of the updated Terms.
        </Section>

        <Section title="13. Governing Law" theme={theme}>
          These Terms shall be governed by and construed in accordance with the laws of the
          jurisdiction in which KivoSoft is registered, without regard to conflict of law
          principles.
        </Section>

        <Section title="14. Contact" theme={theme}>
          For questions about these Terms, contact us at:{'\n\n'}
          📧 support@flirtkey.app{'\n'}
          🌐 https://flirtkey.app/terms
        </Section>

        <Text style={[styles.footer, { color: theme.colors.textTertiary }]}>
          © 2025 KivoSoft. All rights reserved.
        </Text>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

function Section({
  title,
  children,
  theme,
}: {
  title: string;
  children: React.ReactNode;
  theme: any;
}) {
  return (
    <View style={styles.section}>
      <Text style={[styles.sectionTitle, { color: theme.colors.text }]}>{title}</Text>
      <Text style={[styles.sectionBody, { color: theme.colors.textSecondary }]}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
  },
  back: { fontSize: 16 },
  title: { fontSize: 18, fontWeight: 'bold' },
  content: { flex: 1, paddingHorizontal: 20 },
  lastUpdated: { fontSize: 12, marginTop: 16, marginBottom: 8 },
  section: { marginTop: 20 },
  sectionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 8 },
  sectionBody: { fontSize: 14, lineHeight: 22 },
  footer: { fontSize: 12, textAlign: 'center', marginTop: 30 },
});

export default TermsScreen;
